import type { Metadata } from 'next';

import DefaultHeader from '@/common/components/DefaultHeader/DefaultHeader';
import '@/styles/fonts.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <DefaultHeader />
          {children}
        </main>
      </body>
    </html>
  );
}
